/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BanHang_DAO;
import controller.DoanhThu_DAO;
import controller.HoaDon_DAO;
import controller.KhachHang_Dao;
import controller.SanPham_DAO;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BanHang;
import model.DatHang;
import model.DoanhThu;
import model.KhachHang;
import model.SanPham;

/**
 *
 * @author LaptopDT
 */
public class BanHangJDialog extends javax.swing.JDialog {

    private MenuFrm menu;
    private List<SanPham> listSP;
    private List<BanHang> listBH;
    private static List<DoanhThu> listDT;
    private DefaultTableModel modelKH;
    private DefaultTableModel modelBH;
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");// dạng cần chuyển

    public BanHangJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        menu = (MenuFrm) parent;
        initComponents();
        this.setLocationRelativeTo(null);

        listSP = new SanPham_DAO().getListSanPham();
        listDT = new DoanhThu_DAO().getListDoanhThu();

        listBH = new BanHang_DAO().getListBanHang();
        modelBH = (DefaultTableModel) tblBanHang.getModel();

        new SanPham_DAO().initComboBox_TenSanPham(combo_TENSP_BH);
        showBANHANG();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        combo_MASP = new javax.swing.JComboBox<>();
        jLabel95 = new javax.swing.JLabel();
        combo_LOAISP_BH = new javax.swing.JComboBox<>();
        jLabel92 = new javax.swing.JLabel();
        txt_NSX_BH = new javax.swing.JTextField();
        jLabel93 = new javax.swing.JLabel();
        txt_HSD_BH = new javax.swing.JTextField();
        jLabel90 = new javax.swing.JLabel();
        combo_TENSP_BH = new javax.swing.JComboBox<>();
        jLabel91 = new javax.swing.JLabel();
        txt_slNhap_BH = new javax.swing.JTextField();
        jLabel96 = new javax.swing.JLabel();
        txt_TONGSOLUONG_BH = new javax.swing.JTextField();
        txtGiaBan12 = new javax.swing.JLabel();
        txt_GIATIEN_BH = new javax.swing.JTextField();
        txtGiaBan13 = new javax.swing.JLabel();
        txt_TONGTIEN_BH = new javax.swing.JTextField();
        jLabel94 = new javax.swing.JLabel();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblBanHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_TongHoaDon = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        combo_DVtinh_BH = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txt_TienNhan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_TienDu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_MaHD_BH = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel85.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 51, 51));
        jLabel85.setText("BÁN HÀNG");

        jLabel97.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel97.setText("          MÃ SẢN PHẨM");

        jLabel95.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel95.setText("LOẠI SẢN PHẨM");

        jLabel92.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel92.setText("NGÀY SẢN XUẤT");

        jLabel93.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel93.setText("HẠN SỬ DỤNG");

        jLabel90.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel90.setText("TÊN SẢN PHẨM");

        combo_TENSP_BH.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combo_TENSP_BHPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel91.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel91.setText("SỐ LƯỢNG");

        txt_slNhap_BH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_slNhap_BHKeyReleased(evt);
            }
        });

        jLabel96.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel96.setText("/");

        txtGiaBan12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtGiaBan12.setText("GIÁ BÁN");

        txtGiaBan13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtGiaBan13.setText("TỔNG TIỀN");

        txt_TONGTIEN_BH.setEditable(false);
        txt_TONGTIEN_BH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TONGTIEN_BHtxt_Price1ActionPerformed(evt);
            }
        });
        txt_TONGTIEN_BH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TONGTIEN_BHKeyReleased(evt);
            }
        });

        jLabel94.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel94.setText("MÃ ĐƠN HÀNG");

        jButton31.setIcon(new javax.swing.ImageIcon("E:\\QUAN_LY_LINH_KIEN\\Quan_Ly_LinhKien\\src\\Image\\Add.png")); // NOI18N
        jButton31.setText("THÊM SẢN PHẨM");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton32.setIcon(new javax.swing.ImageIcon("E:\\QUAN_LY_LINH_KIEN\\Quan_Ly_LinhKien\\src\\Image\\Delete.png")); // NOI18N
        jButton32.setText("XÓA SẢN PHẨM");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        jButton35.setIcon(new javax.swing.ImageIcon("E:\\QUAN_LY_LINH_KIEN\\Quan_Ly_LinhKien\\src\\Image\\Pay.png")); // NOI18N
        jButton35.setText("THANH TOÁN");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        tblBanHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Thành Tiền"
            }
        ));
        tblBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBanHangMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblBanHang);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("TỔNG TIỀN HÓA ĐƠN");

        txt_TongHoaDon.setEditable(false);
        txt_TongHoaDon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TongHoaDonKeyReleased(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("TÍNH TỔNG TIỀN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("ĐƠN VỊ TÍNH");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Tiền Nhận Của Khách Hàng :");

        txt_TienNhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TienNhanKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Tiền Dư Của Khách:");

        txt_TienDu.setEditable(false);
        txt_TienDu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TienDuKeyReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("E:\\QUAN_LY_LINH_KIEN\\Quan_Ly_LinhKien\\src\\Image\\New.png")); // NOI18N
        jButton1.setText("THÊM HÓA ĐƠN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_MaHD_BH.setEditable(false);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\LaptopDT\\Downloads\\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\\src\\Image\\Refresh-icon.png")); // NOI18N
        jButton3.setText("CẬP NHẬT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_TongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(571, 571, 571)
                        .addComponent(jLabel85)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel94)
                        .addGap(18, 18, 18)
                        .addComponent(txt_MaHD_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(txt_GIATIEN_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel97)
                                .addGap(18, 18, 18)
                                .addComponent(combo_MASP, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel93)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_HSD_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel91)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_slNhap_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel96, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_TONGSOLUONG_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel92)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_NSX_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel90)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo_TENSP_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(txtGiaBan12)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txt_TienNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                                .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel95)
                                .addGap(18, 18, 18)
                                .addComponent(combo_LOAISP_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(combo_DVtinh_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txt_TienDu, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtGiaBan13)
                        .addGap(18, 18, 18)
                        .addComponent(txt_TONGTIEN_BH, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel85)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel90)
                            .addComponent(combo_TENSP_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_LOAISP_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel95)
                            .addComponent(txt_MaHD_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel94))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_NSX_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel92)
                            .addComponent(jLabel8)
                            .addComponent(combo_DVtinh_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtGiaBan12)
                                .addComponent(txt_GIATIEN_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtGiaBan13)
                            .addComponent(txt_TONGTIEN_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel97)
                            .addComponent(combo_MASP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel93)
                            .addComponent(txt_HSD_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel91)
                            .addComponent(txt_slNhap_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel96)
                            .addComponent(txt_TONGSOLUONG_BH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton32, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jButton31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_TongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel9)
                    .addComponent(txt_TienNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_TienDu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("CẬP NHẬT ĐƠN HÀNG\n", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_TENSP_BHPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_TENSP_BHPopupMenuWillBecomeInvisible
        new SanPham_DAO().loadData_SanPham(combo_TENSP_BH, combo_MASP, combo_LOAISP_BH, txt_NSX_BH, txt_HSD_BH, txt_TONGSOLUONG_BH, txt_GIATIEN_BH, combo_DVtinh_BH);
    }//GEN-LAST:event_combo_TENSP_BHPopupMenuWillBecomeInvisible

    private void txt_slNhap_BHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_slNhap_BHKeyReleased
        int soluong, giaBan, TongTien = 0;
        try {
            soluong = Integer.parseInt(txt_slNhap_BH.getText());
            giaBan = Integer.parseInt(txt_GIATIEN_BH.getText());
            TongTien = giaBan * Integer.parseInt(txt_slNhap_BH.getText());
        } catch (NumberFormatException e) {
            System.out.println(e);
        }
        txt_TONGTIEN_BH.setText(String.valueOf(TongTien));
    }//GEN-LAST:event_txt_slNhap_BHKeyReleased

    private void txt_TONGTIEN_BHtxt_Price1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TONGTIEN_BHtxt_Price1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TONGTIEN_BHtxt_Price1ActionPerformed

    public void refresh() {
        int tongSL, slNhap, slConLai;
        slNhap = Integer.parseInt(txt_slNhap_BH.getText());
        tongSL = Integer.parseInt(txt_TONGSOLUONG_BH.getText());
        slConLai = tongSL - slNhap;
        SanPham sp = new SanPham(slConLai);
        String tensp = combo_TENSP_BH.getSelectedItem().toString();
        new SanPham_DAO().Update_SoLuongSP(sp, tensp);
        listSP.clear();
        listSP.addAll(new SanPham_DAO().getListSanPham());

        combo_MASP.removeAllItems();
        combo_LOAISP_BH.removeAllItems();
        txt_GIATIEN_BH.setText("");
        txt_NSX_BH.setText("");
        txt_HSD_BH.setText("");
        txt_TONGTIEN_BH.setText("");
        txt_slNhap_BH.setText("");
        txt_TONGSOLUONG_BH.setText("");

    }

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed

        String maSP = null, maHD = null, tenSP = null;
        int soluong, TongSL;
        int giaBan, TongTien;
        try {
            maSP = combo_MASP.getSelectedItem().toString();
            maHD = txt_MaHD_BH.getText();
            tenSP = combo_TENSP_BH.getSelectedItem().toString();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(rootPane, "Xin nhập lại!!");
        }

        try {
            TongSL = Integer.parseInt(txt_TONGSOLUONG_BH.getText());
            soluong = Integer.parseInt(txt_slNhap_BH.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Xin nhập số lượng");
            return;
        }
        if (soluong > TongSL) {
            JOptionPane.showMessageDialog(rootPane, "Qúa số lượng mua. Số lượng hàng chỉ còn " + TongSL);
            return;
        }

        TongTien = Integer.parseInt(txt_TONGTIEN_BH.getText());
        BanHang hd = new BanHang(maHD, maSP, tenSP, soluong, TongTien);
        new BanHang_DAO().LuuMaHoaDon_BH(hd);
        if (new BanHang_DAO().AddHoaDon(hd)) {
            listBH.add(hd);
            JOptionPane.showMessageDialog(rootPane, "Thêm dữ liệu thành công");
        } else {// nếu trùng khóa chính or v..v
            JOptionPane.showMessageDialog(rootPane, "Thêm dữ liệu không thành công!Do " + maHD + " đã tồn tại");
        }
        showBANHANG();
        refresh();

    }//GEN-LAST:event_jButton31ActionPerformed

    private void txt_TongHoaDonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TongHoaDonKeyReleased

    }//GEN-LAST:event_txt_TongHoaDonKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int tienSP;
        int TongHD = 0;
        for (BanHang a : listBH) {
            tienSP = a.getTongTien();
            TongHD += tienSP;
        }
        txt_TongHoaDon.setText(String.valueOf(TongHD));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_TONGTIEN_BHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TONGTIEN_BHKeyReleased

    }//GEN-LAST:event_txt_TONGTIEN_BHKeyReleased

    private void txt_TienDuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TienDuKeyReleased

    }//GEN-LAST:event_txt_TienDuKeyReleased

    private void txt_TienNhanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TienNhanKeyReleased
        float tienNhan, tongHD, tienDu;
        int tienDu_Real = 0;
        String money = txt_TienNhan.getText();
        String summoney = txt_TongHoaDon.getText();
        try {
            tienNhan = Float.parseFloat(money);
            tongHD = Float.parseFloat(summoney);
            tienDu = tienNhan - tongHD;
            tienDu_Real = (int) (tienDu);
        } catch (NumberFormatException e) {
            System.out.println(e);
        }
        txt_TienDu.setText(String.valueOf(tienDu_Real));
    }//GEN-LAST:event_txt_TienNhanKeyReleased

    static int so() {
        int d = 0;
        List<BanHang> list = new BanHang_DAO().MaDonDatHang();
        if (list.size() > 0) {
            String mahd = list.get(list.size() - 1).getMaHD();
            String so = mahd.substring(2);
            d = Integer.parseInt(so);
        } else {
            d = 0;
        }
        return d;
    }
    static int dem = so();

    static String changeMHD() {
        dem = dem + 1;
        String maHD = "HD";
        maHD += String.valueOf(dem);
        return maHD;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txt_MaHD_BH.setText(changeMHD());
    }//GEN-LAST:event_jButton1ActionPerformed


    private void tblBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBanHangMouseClicked
//        int dong = tblBanHang.getSelectedRow();
//        combo_MASP.removeAllItems();
//        if (dong >= 0) {
//            combo_MASP.addItem(tblBanHang.getValueAt(dong, 1).toString());
//        }
    }//GEN-LAST:event_tblBanHangMouseClicked

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        BanHang s = new BanHang();
        int removeIndex = tblBanHang.getSelectedRow();
        if (removeIndex == -1) {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn 1 dòng rồi ấn Xóa!");
        } else if (listBH.size() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Không có thông tin để Xóa!");
        } else {
            int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa thông tin không?", "Hỏi",
                    JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.NO_OPTION) {
                return;
            }
            s = listBH.get(removeIndex);
            new SanPham_DAO().delectSanPham(s.getMaSP());
            listBH.remove(removeIndex);
            showBANHANG();
        }
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        int tonghd, tiennhan;
        String mahd = txt_MaHD_BH.getText();
        try {
            tonghd = Integer.parseInt(txt_TongHoaDon.getText());
            tiennhan = Integer.parseInt(txt_TienNhan.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Hãy điền đẩy đủ thông tin vào ô trống");
            return;
        }
        String tien_du = txt_TienDu.getText();
        if (Float.parseFloat(tien_du) < 0) {
            JOptionPane.showMessageDialog(rootPane, "Số tiền quý khách trả không đủ");
            return;
        }
        int tiendu = Integer.parseInt(tien_du);
        if (tien_du.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Thanh toán không thành công");
            return;
        }
        DoanhThu dt = new DoanhThu(mahd, tonghd, tiennhan, tiendu);
        for (DoanhThu a : listDT) {
            if (a.getMaHD().equals(mahd)) {
                JOptionPane.showMessageDialog(rootPane, "Mã hóa đơn " + mahd + " đã tồn tại!!Không thanh toán thành công");
                return;
            }
        }
        new DoanhThu_DAO().ThanhToan(dt);
        new BanHang_DAO().delectHoaDonBanHang();
        JOptionPane.showMessageDialog(rootPane, "Thanh toán thành công");
        listBH.clear();
        showBANHANG();
        txt_TONGTIEN_BH.setText("");
        txt_TienNhan.setText("");
        txt_TienDu.setText("");
        txt_TongHoaDon.setText("");
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new SanPham_DAO().initComboBox_TenSanPham(combo_TENSP_BH);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BanHangJDialog dialog = new BanHangJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_DVtinh_BH;
    private javax.swing.JComboBox<String> combo_LOAISP_BH;
    private javax.swing.JComboBox<String> combo_MASP;
    private javax.swing.JComboBox<String> combo_TENSP_BH;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton35;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblBanHang;
    private javax.swing.JLabel txtGiaBan12;
    private javax.swing.JLabel txtGiaBan13;
    private javax.swing.JTextField txt_GIATIEN_BH;
    private javax.swing.JTextField txt_HSD_BH;
    private javax.swing.JTextField txt_MaHD_BH;
    private javax.swing.JTextField txt_NSX_BH;
    private javax.swing.JTextField txt_TONGSOLUONG_BH;
    private javax.swing.JTextField txt_TONGTIEN_BH;
    private javax.swing.JTextField txt_TienDu;
    private javax.swing.JTextField txt_TienNhan;
    private javax.swing.JTextField txt_TongHoaDon;
    private javax.swing.JTextField txt_slNhap_BH;
    // End of variables declaration//GEN-END:variables

    private void showBANHANG() {
        modelBH.setRowCount(0);
        String masp = null, tensp = null;
        for (BanHang hd : listBH) {
            //String ngaydat = sdf.format(hd.getNgayLapHoaDon());
            for (SanPham s : listSP) {
                if (hd.getMaSP().equals(s.getMaSP()) && hd.getTenSP().equals(s.getTenSP())) {
                    masp = s.getMaSP();
                    tensp = s.getTenSP();
                }
            }
            modelBH.addRow(new Object[]{masp, tensp,
                hd.getSoluongMua(), hd.getTongTien()});

        }
    }
}
