/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DoanhThu_DAO;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.DoanhThu;

/**
 *
 * @author LaptopDT
 */
public class DoanhThuJDialog extends javax.swing.JDialog {

    private MenuFrm test;
//    private Connection conn=null;
//    private ResultSet rs;
//    private PreparedStatement ps = null;
    private List<DoanhThu> listDT;
    private DefaultTableModel modelDT;
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    public DoanhThuJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        test = (MenuFrm) parent;
        this.setLocationRelativeTo(null);
        listDT = new DoanhThu_DAO().getListDoanhThu();
        modelDT = (DefaultTableModel) tblDoanhThu.getModel();
        showDoanhThu();
    }

//    private void Connection() {
//        try {
//            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
//            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Do_An_De_04", "sa", "123456");
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(DoanhThuJDialog.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(DoanhThuJDialog.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoanhThu = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_TongTien = new javax.swing.JLabel();
        lbl_TongSoHoaDon = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thống Kê Doanh Thu");

        tblDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Ngày Bán", "Tổng Tiền Thu", "Tổng Tiền Nhận", "Tổng Tiền Dư"
            }
        ));
        jScrollPane1.setViewportView(tblDoanhThu);

        jButton2.setIcon(new javax.swing.ImageIcon("E:\\QUAN_LY_LINH_KIEN\\Quan_Ly_LinhKien\\src\\Image\\Revenue.png")); // NOI18N
        jButton2.setText("Xuất Thống Kê");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tổng Số Hóa Đơn Bán Ra:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tổng Tiền Hóa Đơn:");

        lbl_TongTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_TongSoHoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon("E:\\QUAN_LY_LINH_KIEN\\Quan_Ly_LinhKien\\src\\Image\\Print Sale.png")); // NOI18N
        jButton1.setText("In Danh Sách");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_TongSoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jButton2)
                .addGap(109, 109, 109)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addComponent(lbl_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_TongSoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        List<DoanhThu> list = new ArrayList<>();
//        Date ngay1 = null;
//        LocalDate d1Kiemtra = null;
//        Date ngay2 = null;
//        LocalDate d2Kiemtra = null;
////        String[] d1 = txt_d1.getText().split("/");
////        String[] d2 = txt_d2.getText().split("/");
////        int daysx = 0, monthsx = 0, yearsx = 0,
////                dayhsd = 0, monthhsd = 0, yearhsd = 0;
////        try {
////            daysx = Integer.parseInt(d1[0]);
////            monthsx = Integer.parseInt(d1[1]);
////            yearsx = Integer.parseInt(d1[2]);
////            d1Kiemtra = LocalDate.of(yearsx, monthsx, daysx);
////
////            dayhsd = Integer.parseInt(d2[0]);
////            monthhsd = Integer.parseInt(d2[1]);
////            yearhsd = Integer.parseInt(d2[2]);
////            d2Kiemtra = LocalDate.of(yearhsd, monthhsd, dayhsd);
////        } catch (DateTimeException e) {
////            JOptionPane.showMessageDialog(rootPane, "Lỗi:" + e);
////            return;
////        } catch (NumberFormatException a) {
////            JOptionPane.showMessageDialog(rootPane, "Lỗi:" + a + " Xin nhập lại. VD:22/8/2001");
////            return;
////        }
////        SimpleDateFormat d = new SimpleDateFormat("yyyy/MM/dd");
//        //Date day1 = d.format(ngay1);
//        new DoanhThu_DAO().getListSearch_DoanhThu(ngay1, ngay2, list);
//        listDT.clear();
//        listDT.addAll(list);
//        showDoanhThu();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        exportFile(tblDoanhThu, modelDT);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void exportFile(JTable table, DefaultTableModel model) {
        JFileChooser chooser = new JFileChooser();
        int i = chooser.showSaveDialog(chooser);// hiển thị cửa sổ lưu
        if (i == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            try {
                FileWriter output = new FileWriter(file + ".xls");
                BufferedWriter bw = new BufferedWriter(output);
                //modelSV = (DefaultTableModel) tblSinhVien.getModel();
                model = (DefaultTableModel) table.getModel();
                // ten cot
                for (int j = 0; j < table.getColumnCount(); j++) {
                    bw.write(model.getColumnName(j) + "\t");
                }
                bw.write("\n");
                // lay du lieu dong
                for (int j = 0; j < table.getRowCount(); j++) {
                    for (int k = 0; k < table.getColumnCount(); k++) {
                        bw.write(model.getValueAt(j, k) + "\t");
                    }
                    bw.write("\n");
                }
                bw.close();
                JOptionPane.showMessageDialog(null, "Lưu file thành công!");
            } catch (IOException ex) {
                Logger.getLogger(DoanhThuJDialog.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Lỗi khi lưu file!");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoanhThuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoanhThuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoanhThuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoanhThuJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoanhThuJDialog dialog = new DoanhThuJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_TongSoHoaDon;
    private javax.swing.JLabel lbl_TongTien;
    private javax.swing.JTable tblDoanhThu;
    // End of variables declaration//GEN-END:variables

    private void showDoanhThu() {
        int count = 0, tienSP, TongHD = 0;
        modelDT.setRowCount(0);
        for (DoanhThu dt : listDT) {
            String ngayBan = sdf.format(dt.getNgayDat());
            modelDT.addRow(new Object[]{
                dt.getMaHD(), ngayBan, dt.getTongTienThu(),
                dt.getTienNhan(), dt.getTienDu()
            });
            count++;
        }
        lbl_TongSoHoaDon.setText(String.valueOf(count));
        for (DoanhThu a : listDT) {
            tienSP = a.getTongTienThu();
            TongHD += tienSP;
        }
        lbl_TongTien.setText(String.valueOf(TongHD));
//        tx.setText(String.valueOf(TongHD));
    }
//    private void showDoanhThu() {
//        modelDT.setRowCount(0);
//        String sql = "select * from DoanhThu order by MaHD";
//        try {
//            ps = conn.prepareStatement(sql);
//            rs = ps.executeQuery();
//            while (rs.next()) {
//                Vector vector = new Vector();
//                vector.add(rs.getString(1).trim());
//                vector.add(rs.getDate(2));
//                vector.add(rs.getInt(3));
//                vector.add(rs.getInt(4));
//                vector.add(rs.getInt(5));
//                modelDT.addRow(vector);
//            }
//            tblDoanhThu.setModel(modelDT);
//        } catch (SQLException ex) {
//            Logger.getLogger(DoanhThuJDialog.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
}
