/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerImp;
import controller.DoanhThu_DAO;
import controller.HoaDon_DAO;
import controller.KhachHang_Dao;
import controller.SanPham_DAO;
import java.lang.reflect.Array;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DatHang;
import model.DoanhThu;
import model.KhachHang;
import model.SanPham;

/**
 *
 * @author LaptopDT
 */
public class DonDatHangJDialog extends javax.swing.JDialog {

    private MenuFrm menu;
    private List<KhachHang> listKH;
    private List<SanPham> listSP;
    private List<DatHang> listHD;
    private List<DatHang> listDS;
    private DefaultTableModel modelKH;
    private DefaultTableModel modelHD;
    private DefaultTableModel modelDS;
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");// dạng cần chuyển

    public DonDatHangJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        menu = (MenuFrm) parent;
        initComponents();
        this.setLocationRelativeTo(null);

        listKH = new KhachHang_Dao().getListKH();
        modelKH = (DefaultTableModel) tblKhachHang.getModel();

        listSP = new SanPham_DAO().getListSanPham();

        listHD = new HoaDon_DAO().getListHoaDon();
        modelHD = (DefaultTableModel) tblHoaDon.getModel();

        listDS = new HoaDon_DAO().getList_DS_HoaDon();

        new KhachHang_Dao().initComboBox_KhachHang(combo_MaKH);
        new SanPham_DAO().initComboBox_TenSanPham(combo_TENSP);
        new HoaDon_DAO().initComboBox_MaDH(cbx);

        showKhachHang();
//        showHoaDon();
        //show_DS_HoaDon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        txt_TENKH = new javax.swing.JTextField();
        jLabel101 = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        jLabel102 = new javax.swing.JLabel();
        txt_DIACHI = new javax.swing.JTextField();
        jLabel104 = new javax.swing.JLabel();
        txt_MKH = new javax.swing.JTextField();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        btnADD = new javax.swing.JButton();
        btnRepair = new javax.swing.JButton();
        btnDELETE = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        combo_MaKH = new javax.swing.JComboBox<>();
        jLabel86 = new javax.swing.JLabel();
        txtKH = new javax.swing.JTextField();
        jLabel87 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel89 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel88 = new javax.swing.JLabel();
        txtNgayDat = new javax.swing.JTextField();
        jLabel97 = new javax.swing.JLabel();
        combo_MASP = new javax.swing.JComboBox<>();
        jLabel95 = new javax.swing.JLabel();
        combo_LOAISP = new javax.swing.JComboBox<>();
        jLabel92 = new javax.swing.JLabel();
        txt_NSX = new javax.swing.JTextField();
        jLabel93 = new javax.swing.JLabel();
        txt_HSD = new javax.swing.JTextField();
        jLabel90 = new javax.swing.JLabel();
        combo_TENSP = new javax.swing.JComboBox<>();
        jLabel91 = new javax.swing.JLabel();
        txt_slNhap = new javax.swing.JTextField();
        jLabel96 = new javax.swing.JLabel();
        txt_TONGSOLUONG = new javax.swing.JTextField();
        txtGiaBan12 = new javax.swing.JLabel();
        txt_GIATIEN = new javax.swing.JTextField();
        txtGiaBan13 = new javax.swing.JLabel();
        txt_TONGTIEN = new javax.swing.JTextField();
        jLabel94 = new javax.swing.JLabel();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_TongHoaDon = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        combo_DVtinh = new javax.swing.JComboBox<>();
        cbx = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel99.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(255, 51, 51));
        jLabel99.setText("QUẢN LÝ KHÁCH HÀNG");

        jLabel100.setText("Tên Khách Hàng:");

        jLabel101.setText("Số Điện Thoại:");

        jLabel102.setText("Địa Chỉ:");

        jLabel104.setText("MÃ KHÁCH HÀNG:");

        buttonGroup1.add(rdNam);
        rdNam.setSelected(true);
        rdNam.setText("Nam");
        rdNam.setAutoscrolls(true);
        rdNam.setContentAreaFilled(false);

        buttonGroup1.add(rdNu);
        rdNu.setText("Nữ");

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "Giới Tính", "Địa Chỉ", "SĐT"
            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        btnADD.setText("THÊM");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        btnRepair.setText("SỬA");
        btnRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairActionPerformed(evt);
            }
        });

        btnDELETE.setText("XÓA");
        btnDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel104)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_MKH, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addComponent(jLabel100)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rdNam, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdNu, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_TENKH, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(jLabel101)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel102)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_DIACHI, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(407, 407, 407)
                                .addComponent(jLabel99))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(197, 197, 197)
                                .addComponent(btnRepair, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(204, 204, 204)
                                .addComponent(btnDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel99)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel100)
                    .addComponent(txt_TENKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel104)
                    .addComponent(txt_MKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel101)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel102)
                    .addComponent(txt_DIACHI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdNam)
                    .addComponent(rdNu))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRepair, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("QUẢN LÝ KHÁCH HÀNG", jPanel1);

        jLabel85.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 51, 51));
        jLabel85.setText("CẬP NHẬT ĐƠN ĐẶT HÀNG");

        jLabel98.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel98.setText("MÃ KHÁCH HÀNG:");

        combo_MaKH.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combo_MaKHPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        combo_MaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_MaKHActionPerformed(evt);
            }
        });

        jLabel86.setText("Tên Khách Hàng:");

        jLabel87.setText("Số Điện Thoại:");

        jLabel89.setText("Địa Chỉ:");

        jLabel88.setText("Ngày Đặt:");

        jLabel97.setText("          MÃ SẢN PHẨM");

        jLabel95.setText("LOẠI SẢN PHẨM");

        jLabel92.setText("NGÀY SẢN XUẤT");

        jLabel93.setText("HẠN SỬ DỤNG");

        jLabel90.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel90.setText("TÊN SẢN PHẨM");

        combo_TENSP.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combo_TENSPPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel91.setText("SỐ LƯỢNG");

        txt_slNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_slNhapKeyReleased(evt);
            }
        });

        jLabel96.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel96.setText("/");

        txtGiaBan12.setText("GIÁ BÁN");

        txtGiaBan13.setText("TỔNG TIỀN");

        txt_TONGTIEN.setEditable(false);
        txt_TONGTIEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TONGTIENtxt_Price1ActionPerformed(evt);
            }
        });
        txt_TONGTIEN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TONGTIENKeyReleased(evt);
            }
        });

        jLabel94.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel94.setText("MÃ ĐƠN HÀNG");

        jButton31.setIcon(new javax.swing.ImageIcon("E:\\QUAN_LY_LINH_KIEN\\Quan_Ly_LinhKien\\src\\Image\\Add.png")); // NOI18N
        jButton31.setText("THÊM SẢN PHẨM");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton32.setIcon(new javax.swing.ImageIcon("C:\\Users\\LaptopDT\\Downloads\\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\\src\\Image\\Delete.png")); // NOI18N
        jButton32.setText("XÓA SẢN PHẨM");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        jButton33.setIcon(new javax.swing.ImageIcon("E:\\QUAN_LY_LINH_KIEN\\Quan_Ly_LinhKien\\src\\Image\\New.png")); // NOI18N
        jButton33.setText("THÊM ĐƠN HÀNG");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });

        jButton35.setIcon(new javax.swing.ImageIcon("E:\\QUAN_LY_LINH_KIEN\\Quan_Ly_LinhKien\\src\\Image\\Print Sale.png")); // NOI18N
        jButton35.setText("XUẤT ĐƠN HÀNG");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khách Hàng", "Mã Sản Phẩm", "Tên Sản Phầm", "Ngày đặt", "Số Lượng", "Thành Tiền"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblHoaDon);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LaptopDT\\Downloads\\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\\Quan Ly Cua Hang Mua Ban Thiet Bi Dien Tu\\src\\Image\\Refresh-icon.png")); // NOI18N
        jButton1.setText("CẬP NHẬT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("TỔNG TIỀN HÓA ĐƠN");

        txt_TongHoaDon.setEditable(false);
        txt_TongHoaDon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TongHoaDonKeyReleased(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("TÍNH TỔNG TIỀN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("ĐƠN VỊ TÍNH");

        cbx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxItemStateChanged(evt);
            }
        });
        cbx.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon("E:\\QUAN_LY_LINH_KIEN\\Quan_Ly_LinhKien\\src\\Image\\Delete.png")); // NOI18N
        jButton5.setText("XÓA HÓA ĐƠN");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel88)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtNgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel89)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel86)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtKH, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel87)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel94)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel98)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(114, 114, 114)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel92)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_NSX, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtGiaBan13)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_TONGTIEN, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addComponent(jLabel93)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_HSD, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel91)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txt_slNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel96, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txt_TONGSOLUONG, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jButton32)))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(372, 372, 372)
                                        .addComponent(jLabel95)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(combo_LOAISP, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(combo_DVtinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jButton35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtGiaBan12)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_GIATIEN, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)))
                                .addGap(24, 24, 24))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel90)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo_TENSP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txt_TongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel85)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel97, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(combo_MASP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton33))
                                        .addGap(34, 34, 34)
                                        .addComponent(jButton31)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel98)
                            .addComponent(combo_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel90)
                            .addComponent(combo_TENSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel86)
                            .addComponent(txtKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel87)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel89)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel88)
                            .addComponent(txtNgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel97)
                            .addComponent(combo_MASP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_NSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel92))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGiaBan13)
                            .addComponent(txt_TONGTIEN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaBan12)
                            .addComponent(txt_GIATIEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_LOAISP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel95))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(combo_DVtinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel93)
                                .addComponent(txt_HSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel91)
                            .addComponent(txt_slNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel96)
                            .addComponent(txt_TONGSOLUONG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel94)
                    .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_TongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("CẬP NHẬT ĐƠN HÀNG\n", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("QUẢN LÝ KHÁCH HÀNG");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TONGTIENtxt_Price1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TONGTIENtxt_Price1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TONGTIENtxt_Price1ActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        KhachHang khachHang = new KhachHang();
        String makh, tenkh, gt, diachi, sdt;
        makh = txt_MKH.getText();
        if (makh.length() < 1 || makh.length() > 10) {
            JOptionPane.showMessageDialog(rootPane, "Mã khách hàng chưa hợp lệ, từ 3 đến 10 kí tự");
            return; // nếu sai thì thoát luôn khỏi hàm ko chạy tiếp nữa
        }
        for (KhachHang a : listKH) {
            if (makh.equals(a.getMaKH())) {
                JOptionPane.showMessageDialog(rootPane, "Mã khách hàng bị trùng");
                return;
            }
        }
        khachHang.setMaKH(makh);
        tenkh = txt_TENKH.getText();
        if (tenkh.length() == 0 || tenkh.length() > 50) {
            JOptionPane.showMessageDialog(rootPane, "Tên khách hàng chưa hợp lệ, từ 3 đến 50 kí tự");
            return; // nếu sai thì thoát luôn khỏi hàm ko chạy tiếp nữa
        }
        khachHang.setHoTen(tenkh);
        if (rdNu.isSelected()) {
            khachHang.setGT("Nữ");
        } else {
            khachHang.setGT("Nam");
        }
        diachi = txt_DIACHI.getText();
        if (diachi.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Không để trống địa chỉ");
            return;
        }
        khachHang.setDiaChi(diachi);
        sdt = txt_SDT.getText();
        if (sdt.length() > 12 || sdt.length() < 6) {
            JOptionPane.showMessageDialog(rootPane, "SĐT không hợp lệ. xin nhập lại");
            return;
        }
        khachHang.setPhoneNum(sdt);
        if (new KhachHang_Dao().AddKhachHang(khachHang)) {
            listKH.add(khachHang);
            JOptionPane.showMessageDialog(rootPane, "Thêm dữ liệu thành công");
        } else {// nếu trùng khóa chính or v..v
            JOptionPane.showMessageDialog(rootPane, "Thêm dữ liệu không thành công!");
        }
        showKhachHang();
    }//GEN-LAST:event_btnADDActionPerformed

    private void combo_MaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_MaKHActionPerformed
        //new KhachHang_Dao().loadData_KhachHangCombo(txtKH, txtSDT, txtAddress, combo_MaKH);
    }//GEN-LAST:event_combo_MaKHActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new KhachHang_Dao().initComboBox_KhachHang(combo_MaKH);
        new SanPham_DAO().initComboBox_TenSanPham(combo_TENSP);
        new HoaDon_DAO().initComboBox_MaDH(cbx);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combo_MaKHPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_MaKHPopupMenuWillBecomeInvisible
        new KhachHang_Dao().loadData_KhachHangCombo(txtKH, txtSDT, txtAddress, combo_MaKH);
    }//GEN-LAST:event_combo_MaKHPopupMenuWillBecomeInvisible

    private void btnRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairActionPerformed
        int selectIndex = tblKhachHang.getSelectedRow();
        if (selectIndex == -1) {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn 1 dòng rồi ấn Sửa!");
        } else {
            int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn sửa thông tin không?", "Hỏi",
                    JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.NO_OPTION) {
                return;
            }

            String makh, tenkh, gt = null, diachi, sdt;
            makh = txt_MKH.getText();
            if (makh.length() < 1 || makh.length() > 10) {
                JOptionPane.showMessageDialog(rootPane, "Mã khách hàng chưa hợp lệ, từ 3 đến 10 kí tự");
                return; // nếu sai thì thoát luôn khỏi hàm ko chạy tiếp nữa
            }

            tenkh = txt_TENKH.getText();
            if (tenkh.length() == 0 || tenkh.length() > 50) {
                JOptionPane.showMessageDialog(rootPane, "Tên khách hàng chưa hợp lệ, từ 3 đến 50 kí tự");
                return; // nếu sai thì thoát luôn khỏi hàm ko chạy tiếp nữa
            }

            if (rdNu.isSelected()) {
                gt = "Nữ";
            } else {
                gt = "Nam";
            }
            diachi = txt_DIACHI.getText();
            if (diachi.length() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Không để trống địa chỉ");
                return;
            }

            sdt = txt_SDT.getText();
            if (sdt.length() > 12 || sdt.length() < 6) {
                JOptionPane.showMessageDialog(rootPane, "SĐT không hợp lệ. xin nhập lại");
                return;
            }

            KhachHang khachHang = new KhachHang(makh, tenkh, gt, diachi, sdt);
            String maKHrepair = tblKhachHang.getValueAt(selectIndex, 0).toString();
            new KhachHang_Dao().UpdateKhachHang(khachHang, maKHrepair);
            listKH.add(khachHang);
            JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
        }
        listKH.clear();// xóa hết dữ liệu cũ đi
        listKH.addAll(new KhachHang_Dao().getListKH());
        showKhachHang();
    }//GEN-LAST:event_btnRepairActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        int dong = tblKhachHang.getSelectedRow();
        if (dong >= 0) {
            txt_MKH.setText(tblKhachHang.getValueAt(dong, 0).toString());
            txt_TENKH.setText(tblKhachHang.getValueAt(dong, 1).toString());
            String sex = tblKhachHang.getValueAt(dong, 2).toString();
            if (sex.equals("Nam")) {
                rdNam.setSelected(true);
            } else {
                rdNu.setSelected(true);
            }
            txt_DIACHI.setText(tblKhachHang.getValueAt(dong, 3).toString());
            txt_SDT.setText(tblKhachHang.getValueAt(dong, 4).toString());
        }
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void combo_TENSPPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_TENSPPopupMenuWillBecomeInvisible
        new SanPham_DAO().loadData_SanPham(combo_TENSP, combo_MASP, combo_LOAISP, txt_NSX, txt_HSD, txt_TONGSOLUONG, txt_GIATIEN, combo_DVtinh);
    }//GEN-LAST:event_combo_TENSPPopupMenuWillBecomeInvisible

    public void refresh() {
        int tongSL, slNhap, slConLai;
        slNhap = Integer.parseInt(txt_slNhap.getText());
        tongSL = Integer.parseInt(txt_TONGSOLUONG.getText());
        slConLai = tongSL - slNhap;
        SanPham sp = new SanPham(slConLai);
        String tensp = combo_TENSP.getSelectedItem().toString();
        new SanPham_DAO().Update_SoLuongSP(sp, tensp);
        listSP.clear();
        listSP.addAll(new SanPham_DAO().getListSanPham());

//        txtKH.setText("");
//        txtSDT.setText("");
//        txtAddress.setText("");
//        txtNgayDat.setText("");
        combo_MASP.removeAllItems();
        combo_LOAISP.removeAllItems();
        txt_GIATIEN.setText("");
        txt_NSX.setText("");
        txt_HSD.setText("");
        txt_TONGTIEN.setText("");
        txt_slNhap.setText("");
        txt_TONGSOLUONG.setText("");

    }
    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed

        List<DatHang> list = new ArrayList<>();
        DatHang HD = new DatHang();
        String maSP, maKH;
        String maHD;
        Date ngayDat = null;
        Date ngayHT = null;
        int soluong = 0, TongSL;
        int giaBan, TongTien;

        maSP = combo_MASP.getSelectedItem().toString();
        if (maSP.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Mã sản phẩm trống!Xin nhập lại");
            return;
        }
        maKH = combo_MaKH.getSelectedItem().toString();
//        for (DatHang a : listHD) {
//            if (a.getMaKH().equals(maKH)) {
//                JOptionPane.showMessageDialog(rootPane, "Trùng mã hóa đơn!!");
//                return;
//            }
//        }
//        maHD = txt_MaDH.getText();
        maHD = cbx.getSelectedItem().toString();
        if (maHD.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Mã hóa đơn trống!Xin nhập lại");
            return;
        }
        String[] nd = txtNgayDat.getText().split("/");
        String[] ngayht = sdf.format(new Date()).split("/");
        int day = 0, month = 0, year = 0;
        int dayht = 0, monthht = 0, yearht = 0;
        boolean isOK = true;
        LocalDate SXKiemtra = null;
        LocalDate SXKiemtraHT = null;

        dayht = Integer.parseInt(ngayht[0]);
        monthht = Integer.parseInt(ngayht[1]);
        yearht = Integer.parseInt(ngayht[2]);
        SXKiemtraHT = LocalDate.of(yearht, monthht, dayht);

        try {
            day = Integer.parseInt(nd[0]);
            month = Integer.parseInt(nd[1]);
            year = Integer.parseInt(nd[2]);
            SXKiemtra = LocalDate.of(year, month, day);
        } catch (DateTimeException e) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi:" + e);
            isOK = false;
        } catch (NumberFormatException a) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi:" + a + " Xin nhập lại. VD:22/8/2001");
            isOK = false;
        }
        if (isOK) {
            String dateString = String.format("%d/%d/%d", day, month, year);
            String dateHT = String.format("%d/%d/%d", dayht, monthht, yearht);
            try {
                ngayDat = sdf.parse(dateString);
                ngayHT = sdf.parse(dateHT);
            } catch (ParseException ex) {
                Logger.getLogger(SanPhamJDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (ngayHT.compareTo(ngayDat) > 0) {
            JOptionPane.showMessageDialog(rootPane, "Xin nhập lại ngày đặt hàng");
            return;
        }

        TongSL = Integer.parseInt(txt_TONGSOLUONG.getText());
        try {
            soluong = Integer.parseInt(txt_slNhap.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Số lượng phải là số");
            System.out.println(e);
            return;
        }
        if (soluong > TongSL) {
            JOptionPane.showMessageDialog(rootPane, "Qúa số lượng mua. Số lượng hàng chỉ còn " + TongSL);
            return;
        }

        TongTien = Integer.parseInt(txt_TONGTIEN.getText());
        DatHang hd = new DatHang(maHD, maKH, ngayDat, maSP, soluong, TongTien);
        new HoaDon_DAO().LuuMaHoaDon(hd);
        if (new HoaDon_DAO().AddHoaDon(hd)) {
            list.add(hd);
            JOptionPane.showMessageDialog(rootPane, "Thêm dữ liệu thành công");
        } else {// nếu trùng khóa chính or v..v
            JOptionPane.showMessageDialog(rootPane, "Thêm dữ liệu không thành công!");
        }
        listHD.addAll(list);
        showHoaDon();
        refresh();
    }//GEN-LAST:event_jButton31ActionPerformed

    private void txt_slNhapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_slNhapKeyReleased
        int soluong = Integer.parseInt(txt_slNhap.getText());
        int giaBan = Integer.parseInt(txt_GIATIEN.getText());
        int TongTien = 0;
        TongTien = giaBan * Integer.parseInt(txt_slNhap.getText());
        txt_TONGTIEN.setText(String.valueOf(TongTien));    }//GEN-LAST:event_txt_slNhapKeyReleased

    private void btnDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDELETEActionPerformed

    private void txt_TongHoaDonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TongHoaDonKeyReleased
//        int tienSP;
//        int TongHD = 0;
//        for (DatHang a : listHD) {
//            tienSP = a.getTongTien();
//            TongHD += tienSP;
//        }
//        txt_TongHoaDon.setText(String.valueOf(TongHD));
    }//GEN-LAST:event_txt_TongHoaDonKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int tienSP;
        int TongHD = 0;
        for (DatHang a : listHD) {
            tienSP = a.getTongTien();
            TongHD += tienSP;
        }
        txt_TongHoaDon.setText(String.valueOf(TongHD));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_TONGTIENKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TONGTIENKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TONGTIENKeyReleased

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        DatHang s = new DatHang();
        int tongSL, slNhap, slConLai;
        int removeIndex = tblHoaDon.getSelectedRow();
        if (removeIndex == -1) {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn 1 dòng rồi ấn Xóa!");
        } else if (listHD.size() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Không có thông tin để Xóa!");
        } else {
            int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa thông tin không?", "Hỏi",
                    JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.NO_OPTION) {
                return;
            }
            slNhap = Integer.parseInt(txt_slNhap.getText());
            tongSL = Integer.parseInt(txt_TONGSOLUONG.getText());
            slConLai = tongSL + slNhap;
            SanPham sp = new SanPham(slConLai);
            String tensp = combo_TENSP.getSelectedItem().toString();
            new SanPham_DAO().Update_SoLuongSP(sp, tensp);

            s = listHD.get(removeIndex);
            new HoaDon_DAO().delectSanPham(s.getMaSP());
            listHD.remove(removeIndex);
            showHoaDon();
        }

    }//GEN-LAST:event_jButton32ActionPerformed

    static int so() {
        int d = 0;
        List<DatHang> list = new HoaDon_DAO().MaDonDatHang();
        if (list.size() > 0) {
            String mahd = list.get(list.size() - 1).getMaHD();
            String so = mahd.substring(2);
            d = Integer.parseInt(so);
        } else {
            d = 0;
        }
        return d;
    }
    static int dem = so();

    static String changeMHD() {
        dem = dem + 1;
        String maHD = "DH";
        maHD += String.valueOf(dem);
        return maHD;
    }
    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
//        txt_MaDH.setText(changeMHD());
        cbx.addItem(changeMHD());
        listDS.clear();
        txtKH.setText("");
        txtSDT.setText("");
        txtAddress.setText("");
        txtNgayDat.setText("");
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        List<DoanhThu> listDT = new DoanhThu_DAO().getListDoanhThu();
        String maHD;
        Date ngayDat = null;
        Date ngayHT = null;
        int soluong, TongSL;
        int giaBan, TongTien;

        maHD = cbx.getSelectedItem().toString();
        for (DoanhThu a : listDT) {
            if (a.getMaHD().equals(maHD)) {
                JOptionPane.showMessageDialog(rootPane, "Mã hóa đơn " + maHD + " đã tồn tại. Xin tạo mới hóa đơn khác");
                return;
            }
        }
        int i = cbx.getSelectedIndex();
        String strTongTien = txt_TongHoaDon.getText();
        TongTien = Integer.parseInt(strTongTien);
        DoanhThu dt = new DoanhThu(maHD, TongTien, TongTien, 0);
        if (strTongTien.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Tính tổng tiền hóa đơn!!!");
            return;
        } else {
            new DoanhThu_DAO().ThanhToan(dt);
            new HoaDon_DAO().delectHD(cbx);
            JOptionPane.showMessageDialog(rootPane, "Lưu đơn thành công");
        }

        listHD.clear();
        showHoaDon();
        txtKH.setText("");
        txtSDT.setText("");
        txtAddress.setText("");
        txtNgayDat.setText("");
        txt_TongHoaDon.setText("");
    }//GEN-LAST:event_jButton35ActionPerformed

    private void cbxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbxPopupMenuWillBecomeInvisible
        String mahd = cbx.getSelectedItem().toString();
//        txtNgayDat.setText(tblHoaDon.getValueAt(mahd, 3).toString());
        List<DatHang> listS = new ArrayList<>();
        new HoaDon_DAO().ListSearch_DS_HoaDon(mahd, listS);
        listHD.clear();
        listHD.addAll(listS);
        showHoaDon();
    }//GEN-LAST:event_cbxPopupMenuWillBecomeInvisible

    private void cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxActionPerformed

    }//GEN-LAST:event_cbxActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        cbx.removeItemAt(cbx.getSelectedIndex());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        int dong = tblHoaDon.getSelectedRow();
//        slNhap = Integer.parseInt(txt_slNhap.getText());
//            tongSL = Integer.parseInt(txt_TONGSOLUONG.getText());
//            slConLai = tongSL + slNhap;
//            SanPham sp = new SanPham(slConLai);
//            String tensp = combo_TENSP.getSelectedItem().toString();
        if (dong >= 0) {
            combo_TENSP.setSelectedItem(tblHoaDon.getValueAt(dong, 2).toString());
            txt_slNhap.setText(tblHoaDon.getValueAt(dong, 4).toString());
            txtNgayDat.setText(tblHoaDon.getValueAt(dong, 3).toString());
            combo_MaKH.setSelectedItem(tblHoaDon.getValueAt(dong, 0).toString());
        }
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void cbxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonDatHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonDatHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonDatHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonDatHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DonDatHangJDialog dialog = new DonDatHangJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnDELETE;
    private javax.swing.JButton btnRepair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbx;
    private javax.swing.JComboBox<String> combo_DVtinh;
    private javax.swing.JComboBox<String> combo_LOAISP;
    private javax.swing.JComboBox<String> combo_MASP;
    private javax.swing.JComboBox<String> combo_MaKH;
    private javax.swing.JComboBox<String> combo_TENSP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JLabel txtGiaBan12;
    private javax.swing.JLabel txtGiaBan13;
    private javax.swing.JTextField txtKH;
    private javax.swing.JTextField txtNgayDat;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txt_DIACHI;
    private javax.swing.JTextField txt_GIATIEN;
    private javax.swing.JTextField txt_HSD;
    private javax.swing.JTextField txt_MKH;
    private javax.swing.JTextField txt_NSX;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TENKH;
    private javax.swing.JTextField txt_TONGSOLUONG;
    private javax.swing.JTextField txt_TONGTIEN;
    private javax.swing.JTextField txt_TongHoaDon;
    private javax.swing.JTextField txt_slNhap;
    // End of variables declaration//GEN-END:variables

    private void showKhachHang() {
        modelKH.setRowCount(0);
        for (KhachHang a : listKH) {
            modelKH.addRow(new Object[]{a.getMaKH(), a.getHoTen(), a.getGT(),
                a.getDiaChi(), a.getPhoneNum()});
        }
    }

    private void showHoaDon() {
        modelHD.setRowCount(0);
        String makh = null, tensp = null;
        for (DatHang hd : listHD) {
            String ngaydat = sdf.format(hd.getNgayLapHoaDon());
            for (SanPham s : listSP) {
                if (hd.getMaSP().equals(s.getMaSP())) {
                    tensp = s.getTenSP();
                }
            }
            for (KhachHang a : listKH) {
                if (hd.getMaKH().equals(a.getMaKH())) {
                    makh = a.getMaKH();
                }
            }
            modelHD.addRow(new Object[]{makh, hd.getMaSP(),
                tensp, ngaydat, hd.getSoLuongMua(), hd.getTongTien()});

        }
    }

    private void show_DS_HoaDon() {
        modelDS.setRowCount(0);
        String makh = null, tensp = null;
        for (DatHang hd : listDS) {
            String ngaydat = sdf.format(hd.getNgayLapHoaDon());
            modelDS.addRow(new Object[]{hd.getMaHD(), hd.getMaSP(),
                hd.getTenSP(), hd.getMaKH(), hd.getTenKH(), ngaydat,
                hd.getSoLuongMua(), hd.getTongTien()});
        }
    }
}
